# Generated by Django 5.1 on 2024-08-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_alter_article_options_alter_article_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='home.category', verbose_name='دسته بندی'),
        ),
    ]
